export const SET_NAME = 'SET_NAME'
export const SET_LAST_NAME = 'SET_LAST_NAME'
export const SET_EMAIL = 'SET_EMAIL'
export const SET_AGE = 'SET_AGE'
export const SET_IMAGE = 'SET_IMAGE'
export const RESET_STATE = 'RESET_STATE'